# Generated by Django 4.1.7 on 2023-03-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0002_alter_brand_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, upload_to='Brand/Images'),
        ),
    ]
