# Generated by Django 4.1.7 on 2023-03-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_customer_date_added'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
