# Generated by Django 4.1.7 on 2023-03-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_customer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
