# Generated by Django 4.1.7 on 2023-03-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_customer_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_updated',
            field=models.DateTimeField(),
        ),
    ]
