# Generated by Django 4.1.7 on 2023-03-23 08:53

import Customer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Brand', '0003_alter_brand_brand_image'),
        ('Customer', '0008_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_added_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brand.brand'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(default=Customer.models.customer_number_unique, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
