# Generated by Django 4.1.7 on 2023-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_alter_customer_added_by_alter_customer_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
    ]
