# Generated by Django 4.1.7 on 2023-03-23 07:35

import Product.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brand', '0002_alter_brand_table'),
        ('Customer', '0006_alter_customer_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_number', models.CharField(default=Product.models.product_number_unique, max_length=50)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('PHP', 'Philipine Peso')], default='PHP', max_length=3)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(default='Product Description')),
                ('next_billing_date', models.DateField(auto_now=True)),
                ('previous_billing_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_terminated', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brand.brand')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customer')),
            ],
        ),
    ]
