# Generated by Django 4.1.7 on 2023-03-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_terminated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='next_billing_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='previous_billing_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
