# Generated by Django 4.1.7 on 2023-03-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_rename_product_number_product_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='next_billing_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='previous_billing_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=10),
        ),
    ]
