# Generated by Django 4.1.7 on 2023-03-23 09:16

import Invoice.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0010_alter_customer_is_active_and_more'),
        ('Product', '0007_product_status_alter_product_added_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=Invoice.models.invoice_number_unique, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_price', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
            options={
                'db_table': 'Invoice',
            },
        ),
    ]
