# Generated by Django 4.1.7 on 2023-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_product_is_active_and_more'),
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ManyToManyField(blank=True, to='Product.product'),
        ),
    ]
